version: "3"

services:
  todosDB:
    image: postgres:15.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - "80:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  #     PGADMIN_DEFAULT_PASSWORD: "admin"
  #   depends_on:
  #     - postgres
